[package]
name = "tslink"
version = "0.1.0"
edition = "2021"
authors = ["d.astafyev@outlook.com"]

[lib]
name = "tslink"
proc-macro = true

[dependencies]
convert_case = "0.6.0"
lazy_static = "1.4.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.68"
quote = "1.0.33"
serde = { version="1.0.189", features=["derive"] }
syn = { version="2.0.37", features=["full","fold"] }
thiserror = "1.0.50"
toml = "0.8.2"
