name: Checks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node manager
        run: yarn global add n 
      - name: Install latest node
        run: sudo n stable
      - name: Update rust
        run: rustup update
      - name: Install nightly
        run: rustup install nightly
      - name: Add nightly toolchain
        run: rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Linting
        run: cargo +nightly clippy --all --all-features -- -D warnings
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node manager
        run: yarn global add n 
      - name: Install latest node
        run: sudo n stable
      - name: Update rust
        run: rustup update
      - name: Doc tests
        run: cargo test -- --nocapture
      - name: Callbacks compilation test
        working-directory: ./tests/callbacks
        run: yarn run test
      - name: Renaming compilation test
        working-directory: ./tests/renaming
        run: yarn run test
      - name: Install nj-cli
        run: cargo install nj-cli
      - name: NodeBindgen tests
        working-directory: ./tests/node-bindgen
        run: yarn run test